# Generated by Django 4.2.5 on 2023-09-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
