## Listas

Las listas son estructuras de datos que permiten almacenar varios elementos en una sola variable. Aprenderemos cómo crear y manipular listas en Python.

## Conceptos Clave:

### Listas

Secuencias ordenadas de elementos que pueden ser de diferentes tipos.

### Índices

Números que indican la posición de un elemento en la lista.

### Acceso a Elementos

Se utiliza el índice para acceder a un elemento específico de la lista.

## Ejemplo

```python
frutas = ["manzana", "banana", "naranja", "uva"]
primer_fruta = frutas[0]
segunda_fruta = frutas[1]
```
## Explicación

En este ejemplo, se crea una lista de frutas y se accede a elementos individuales utilizando índices.

Los índices comienzan desde 0, por lo que la primera fruta tiene el índice 0.

::: {.callout-important}
### Actividad Práctica:

Crea una lista con los nombres de tus tres películas favoritas.

Accede al segundo elemento de la lista e imprímelo en la consola.
::: 

## Explicación de la Actividad:

Esta actividad permite a los participantes practicar la creación de listas y el acceso a elementos utilizando índices. Les ayuda a comprender cómo organizar y acceder a múltiples elementos en una sola variable.

