---
title: "Introducción a Python"
# subtitle: "Modelos Discretos"
date: "today"
author: "Lcdo. Diego Medardo Saavedra García. Mgtr."
lang: "es"
format: 
  beamer: 
    aspectratio: 32
    navigation: horizontal
    theme: AnnArbor
    colortheme: lily

# format:
#   revealjs:
#     #chalkboard: 
#       #buttons: false
#     toc: true
#     incremental: false
#     slide-number: true
#     preview-links: auto
#     # logo: img/logo.png
#     # footer: <https://espe.edu.ec>
#     theme: dark
#     makeindex: true
#     multiplex: true
#     transition: fade
#     chalkboard: true #Pizarra
#     auto-stretch: false
#     smaller: false
#     scrollable: true
#     #presentation-title-slide-text-alig: left
#     presentation-slide-text-align: center
#     menu: true
#     codeBlock: {data-trim: true}
#     execute: true
#     executeCode: true
#   #html: 
    
#     #code-fold: true
#     #html-math-method: katex
#     #multiplex: true
#     #transition: fade
#     #auto-stretch: false

editor_options: 
  chunk_output_type: console
---
## Introducción a Python.

**Objetivo:** Comprender los fundamentos de Python como lenguaje de programación y su importancia en el desarrollo de software.

---

### ¿Qué es Python?

- Lenguaje de programación de alto nivel y fácil de aprender.
- Creado por Guido van Rossum en los años 90.
- Sintaxis sencilla y legible.

---

### Historia y Popularidad

- Creado como un proyecto de hobby.
- Popularidad creciente en la comunidad de desarrollo.
- Utilizado por empresas como Google, Facebook y NASA.

---

### Características Clave

- Interpretado y multiplataforma.
- Amplia biblioteca estándar.
- Orientado a objetos y estructurado.

---

### Ventajas y Casos de Uso

- Facilidad de aprendizaje.
- Amplias aplicaciones: desarrollo web, análisis de datos, automatización, etc.
- Comunidad activa y recursos en línea.

---

### Ejemplo Práctico

```python
# Hola Mundo en Python
print("¡Hola, mundo!")
```
## Pregunta de Reflexión

- ¿Por qué crees que Python es una elección popular para principiantes y profesionales en programación?

## Referencias: 

Python.org, "Python Crash Course" by Eric Matthes.