## While loop

En esta lección, profundizaremos en el uso de la estructura while para crear bucles que se ejecutan repetidamente mientras se cumpla una condición, y aprenderemos a utilizar la sentencia break para salir de un bucle.

## Conceptos Clave:

### Sentencia break: 

Se utiliza para salir de un bucle antes de que la condición sea falsa.

### Bucles Infinitos:

Si no se maneja adecuadamente, un bucle while puede ejecutarse infinitamente.

## Ejemplo:

``` python
contador = 0

while True:
    print("Contador:", contador)
    contador += 1
    if contador >= 5:
        break
```
## Explicación:

En este ejemplo, se utiliza un bucle while que se ejecuta infinitamente.

Se utiliza la sentencia break para salir del bucle cuando el contador llega a 5.

::: {.callout-important}
### Actividad Práctica:

Crea un bucle while que pida al usuario ingresar un número positivo menor que 10.

Utiliza la sentencia break para salir del bucle una vez que el usuario ingrese un número válido.
:::

## Explicación de la Actividad:

Esta actividad permite a los participantes practicar el uso de la sentencia break para controlar la ejecución de un bucle while y evitar bucles infinitos. Les ayuda a comprender cómo manejar situaciones en las que es necesario salir de un bucle antes de que la condición sea falsa.

