## If, elif y else

En esta lección, continuaremos trabajando con la estructura if, elif y else, pero esta vez exploraremos cómo anidar estas estructuras para manejar situaciones más complejas.

## Conceptos Clave:

### Anidación de Estructuras

Posibilidad de colocar una estructura if, elif y else dentro de otra.

### Jerarquía de Condiciones

Se evalúan las condiciones de manera secuencial y se ejecuta el primer bloque de código correspondiente a una condición verdadera.

## Ejemplo

``` python
edad = 16
permiso_padres = True

if edad >= 18:
    print("Eres mayor de edad.")
else:
    if permiso_padres:
        print("Eres menor de edad pero tienes permiso de tus padres.")
    else:
        print("Eres menor de edad y no tienes permiso de tus padres.")
```
## Explicación:

En este ejemplo, se anidan estructuras if para manejar diferentes casos basados en la edad y el permiso de los padres.

::: {.callout-important}
### Actividad Práctica:

Crea una variable que represente si un usuario está registrado en un sitio web.

Si el usuario está registrado, muestra un mensaje de bienvenida. Si no está registrado, muestra un mensaje que lo invite a registrarse.
:::

## Explicación de la Actividad:

Esta actividad permite a los participantes practicar la anidación de estructuras if, elif y else para manejar situaciones con múltiples condiciones. Les ayuda a comprender cómo trabajar con jerarquías de condiciones y cómo manejar casos más complejos en sus programas.

