{
  "hash": "204f701e9b1db65ed2d798451a3728c8",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Desafío 4: Calculadora de IMC\"\ndifficulty: \"⭐⭐ Media\"\nestimated_time: \"12 minutos\"\n---\n\n## Situación\n\nUn centro de bienestar necesita una calculadora de Índice de Masa Corporal (IMC). El IMC se calcula dividiendo el peso en kilogramos entre el cuadrado de la estatura en metros. El programa debe además clasificar el resultado.\n\n## Tu misión\n\nCrea un programa que:\n\n1. Pida el nombre de la persona\n2. Pida el peso en kilogramos\n3. Pida la estatura en metros (ejemplo: 1.75)\n4. Calcule el IMC: `peso / (estatura ** 2)`\n5. Clasifique el resultado según la tabla de la OMS\n6. Muestre un reporte completo\n\n### Tabla de clasificación OMS\n\n| IMC | Clasificación |\n|-----|---------------|\n| Menor a 18.5 | Bajo peso |\n| 18.5 a 24.9 | Peso normal |\n| 25.0 a 29.9 | Sobrepeso |\n| 30.0 o más | Obesidad |\n\n## Ejemplo de ejecución\n\n```\n=== CALCULADORA DE IMC ===\n\nNombre: María\nPeso (kg): 70\nEstatura (m): 1.65\n\n--- Reporte de salud ---\nPaciente: María\nIMC: 25.71\nClasificación: Sobrepeso\nRecomendación: Consulta con un nutricionista\n```\n\n## Pista\n\n- `estatura ** 2` eleva al cuadrado\n- Puedes encadenar comparaciones: `18.5 <= imc < 25.0`\n- Usa variables descriptivas para cada clasificación\n\n## Criterios de éxito\n\n- [ ] Calcula el IMC correctamente\n- [ ] Clasifica según la tabla OMS\n- [ ] Muestra el IMC con 2 decimales\n- [ ] Incluye una recomendación básica\n\n<details>\n<summary>Ver solución de referencia</summary>\n\n::: {#e0a967af .cell execution_count=1}\n``` {.python .cell-code}\n# Desafío 4: Calculadora de IMC\n# Solución de referencia\n\nprint(\"=== CALCULADORA DE IMC ===\")\nprint()\n\nnombre = input(\"Nombre: \").strip()\npeso_kg = float(input(\"Peso (kg): \"))\nestatura_m = float(input(\"Estatura (m): \"))\n\nimc = peso_kg / (estatura_m ** 2)\n\nif imc < 18.5:\n    clasificacion = \"Bajo peso\"\n    recomendacion = \"Consulta con un nutricionista para ganar peso saludablemente\"\nelif imc < 25.0:\n    clasificacion = \"Peso normal\"\n    recomendacion = \"¡Excelente! Mantén tus hábitos saludables\"\nelif imc < 30.0:\n    clasificacion = \"Sobrepeso\"\n    recomendacion = \"Consulta con un nutricionista para ajustar tu dieta\"\nelse:\n    clasificacion = \"Obesidad\"\n    recomendacion = \"Consulta con un médico para un plan de tratamiento\"\n\nprint()\nprint(\"--- Reporte de salud ---\")\nprint(f\"Paciente: {nombre}\")\nprint(f\"IMC: {imc:.2f}\")\nprint(f\"Clasificación: {clasificacion}\")\nprint(f\"Recomendación: {recomendacion}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== CALCULADORA DE IMC ===\n\n```\n:::\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">StdinNotImplementedError</span>                  Traceback (most recent call last)\n<span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[1]</span><span class=\"ansi-green-fg\">, line 7</span>\n<span class=\"ansi-green-fg\">      4</span> <span style=\"color:rgb(0,135,0)\">print</span>(<span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">=== CALCULADORA DE IMC ===</span><span class=\"ansi-yellow-fg\">\"</span>)\n<span class=\"ansi-green-fg\">      5</span> <span style=\"color:rgb(0,135,0)\">print</span>()\n<span class=\"ansi-green-fg\">----&gt; </span><span class=\"ansi-green-fg\">7</span> nombre = <span style=\"color:rgb(0,135,0)\" class=\"ansi-yellow-bg\">input</span><span class=\"ansi-yellow-bg\">(</span><span class=\"ansi-yellow-fg ansi-yellow-bg\">\"</span><span class=\"ansi-yellow-fg ansi-yellow-bg\">Nombre: </span><span class=\"ansi-yellow-fg ansi-yellow-bg\">\"</span><span class=\"ansi-yellow-bg\">)</span>.strip()\n<span class=\"ansi-green-fg\">      8</span> peso_kg = <span style=\"color:rgb(0,135,0)\">float</span>(<span style=\"color:rgb(0,135,0)\">input</span>(<span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">Peso (kg): </span><span class=\"ansi-yellow-fg\">\"</span>))\n<span class=\"ansi-green-fg\">      9</span> estatura_m = <span style=\"color:rgb(0,135,0)\">float</span>(<span style=\"color:rgb(0,135,0)\">input</span>(<span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">Estatura (m): </span><span class=\"ansi-yellow-fg\">\"</span>))\n\n<span class=\"ansi-cyan-fg\">File </span><span class=\"ansi-green-fg\">/opt/homebrew/lib/python3.14/site-packages/ipykernel/kernelbase.py:1395</span>, in <span class=\"ansi-cyan-fg\">Kernel.raw_input</span><span class=\"ansi-blue-fg\">(self, prompt)</span>\n<span class=\"ansi-green-fg\">   1393</span> <span style=\"font-weight:bold;color:rgb(0,135,0)\">if</span> <span style=\"font-weight:bold;color:rgb(175,0,255)\">not</span> <span style=\"color:rgb(0,135,0)\">self</span>._allow_stdin:\n<span class=\"ansi-green-fg\">   1394</span>     msg = <span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">raw_input was called, but this frontend does not support input requests.</span><span class=\"ansi-yellow-fg\">\"</span>\n<span class=\"ansi-green-fg\">-&gt; </span><span class=\"ansi-green-fg\">1395</span>     <span style=\"font-weight:bold;color:rgb(0,135,0)\">raise</span> StdinNotImplementedError(msg)\n<span class=\"ansi-green-fg\">   1396</span> <span style=\"font-weight:bold;color:rgb(0,135,0)\">return</span> <span style=\"color:rgb(0,135,0)\">self</span>._input_request(\n<span class=\"ansi-green-fg\">   1397</span>     <span style=\"color:rgb(0,135,0)\">str</span>(prompt),\n<span class=\"ansi-green-fg\">   1398</span>     <span style=\"color:rgb(0,135,0)\">self</span>._get_shell_context_var(<span style=\"color:rgb(0,135,0)\">self</span>._shell_parent_ident),\n<span class=\"ansi-green-fg\">   1399</span>     <span style=\"color:rgb(0,135,0)\">self</span>.get_parent(<span class=\"ansi-yellow-fg\">\"</span><span class=\"ansi-yellow-fg\">shell</span><span class=\"ansi-yellow-fg\">\"</span>),\n<span class=\"ansi-green-fg\">   1400</span>     password=<span style=\"font-weight:bold;color:rgb(0,135,0)\">False</span>,\n<span class=\"ansi-green-fg\">   1401</span> )\n\n<span class=\"ansi-red-fg\">StdinNotImplementedError</span>: raw_input was called, but this frontend does not support input requests.</pre>\n```\n:::\n\n:::\n:::\n\n\n</details>\n\n---\n\n[← Desafío 3](03-conversor-moneda.qmd) | [Desafío 5 →](05-historia-interactiva.qmd)\n\n",
    "supporting": [
      "04-calculadora-imc_files"
    ],
    "filters": [],
    "includes": {}
  }
}