## Variables

Las variables son fundamentales en la programación ya que permiten almacenar y manipular datos. Aprenderemos cómo declarar y utilizar variables en Python.

## Conceptos Clave:

### Variables

Nombres que representan ubicaciones de memoria donde se almacenan datos.

### Declaración de Variables.

- Asignación de un valor a un nombre utilizando el operador "=".
- Convenciones de Nombres: Siguen reglas para ser descriptivos y seguir una estructura (por ejemplo, letras minúsculas y guiones bajos para espacios).

## Ejemplo

``` python
nombre = "Ana"
edad = 30
saldo_bancario = 1500.75
es_mayor_de_edad = True
```

## Explicación:

En este ejemplo, se declaran variables para almacenar el nombre de una persona, su edad, su saldo bancario y un valor booleano que indica si es mayor de edad.

Los nombres de variables son descriptivos y siguen la convención de nombres recomendada (letras minúsculas y guiones bajos para espacios).

::: {.callout-important}

### Actividad Práctica

Crea variables para almacenar información personal, como tu ciudad, tu edad y tu ocupación.

Declara variables para almacenar cantidades numéricas, como el precio de un producto y la cantidad de unidades disponibles.
::: 

## Explicación de la Actividad

Esta actividad permite a los participantes practicar la declaración de variables en Python y aplicar el concepto de convenciones de nombres. 

Les ayuda a comprender cómo almacenar y acceder a datos utilizando variables descriptivas y significativas.
