## Introducción a Funciones

En esta lección, nos adentraremos en el mundo de las funciones en Python, una de las características más poderosas del lenguaje. Aprenderemos cómo **definir funciones**, **pasar argumentos** y **retornar valores**.

### Conceptos Clave

#### Funciones:

Son bloques de código reutilizables que realizan tareas específicas. Las funciones permiten dividir el código en partes más pequeñas y manejables, lo que facilita la lectura, la depuración y la reutilización del código.

### Definición de Funciones

Para crear una función en Python, utilizamos la palabra clave def, seguida del nombre de la función y paréntesis. Veamos un ejemplo:

```python
def saludar(nombre):
    return "Hola, " + nombre
```
En este caso, hemos definido una función llamada saludar que toma un argumento llamado nombre.

### Argumentos

Los argumentos son valores que se pasan a una función para que trabaje con ellos. En el ejemplo anterior, nombre es un argumento que se utiliza para personalizar el saludo.

### Retorno de Valores

Una función puede devolver un valor utilizando la palabra clave return. En nuestro ejemplo, la función saludar retorna un saludo personalizado. Veamos cómo se utiliza:

```python
mensaje = saludar("Juan")
print(mensaje)
```
En este fragmento de código, hemos llamado a la función saludar pasando el argumento "Juan". La función devuelve "Hola, Juan", que se almacena en la variable mensaje y se muestra en la consola.

:::{.callout-tip}
**Actividad Práctica**

Ahora, pondremos en práctica lo que hemos aprendido. Tu tarea es crear una función llamada calcular_cuadrado que reciba un número como argumento y retorne el cuadrado de ese número.

```python
def calcular_cuadrado(numero):
    return numero ** 2

resultado = calcular_cuadrado(5)
print("El cuadrado es:", resultado)
```
En este ejemplo, hemos definido la función calcular_cuadrado que toma un número como argumento, lo eleva al cuadrado y lo retorna. Luego, llamamos a esta función con el número 5 y mostramos el resultado en la consola.
:::
### Explicación de la Actividad

Esta actividad te permitirá practicar la creación y uso de funciones en Python. Aprenderás cómo definir una función que realice un cálculo específico y cómo utilizarla para obtener resultados. Las funciones son una parte fundamental de la programación en Python y te ayudarán a escribir código más organizado y eficiente.