# Variables y Variables Múltiples

## Variables

Las variables son fundamentales en la programación ya que permiten almacenar y manipular datos. Aprenderemos cómo declarar y utilizar variables en Python.

### Conceptos Clave

**Variables**

- Nombres que representan ubicaciones de memoria donde se almacenan datos.

**Declaración de Variables**

- Asignación de un valor a un nombre utilizando el operador "=".
- Convenciones de Nombres: Siguen reglas para ser descriptivos y seguir una estructura (por ejemplo, letras minúsculas y guiones bajos para espacios).

**Ejemplo**:

```python
nombre = "Ana"
edad = 30
saldo_bancario = 1500.75
es_mayor_de_edad = True
```

En este ejemplo, se declaran variables para almacenar el nombre de una persona, su edad, su saldo bancario y un valor booleano que indica si es mayor de edad.

Los nombres de variables son descriptivos y siguen la convención de nombres recomendada (letras minúsculas y guiones bajos para espacios).

:::{.callout-tip}

### Actividad Práctica

1. Crea variables para almacenar información personal, como tu ciudad, tu edad y tu ocupación.

2. Declara variables para almacenar cantidades numéricas, como el precio de un producto y la cantidad de unidades disponibles.

:::

## Explicación de la Actividad.

Esta actividad permite a los participantes practicar la declaración de variables en Python y aplicar el concepto de convenciones de nombres. Les ayuda a comprender cómo almacenar y acceder a datos utilizando variables descriptivas y significativas.
Múltiples Variables

En Python, es posible asignar valores a múltiples variables en una sola línea. Aprenderemos cómo declarar y utilizar múltiples variables de manera eficiente.

### Conceptos Clave

**Asignación Múltiple**

- Permite asignar valores a varias variables en una línea.

**Desempaquetado de Valores**

- Se pueden asignar valores de una lista o tupla a múltiples variables en una sola operación.

**Intercambio de Valores**

- Se pueden intercambiar los valores de dos variables utilizando asignación múltiple.

**Ejemplo**:

```python
nombre, edad, altura = "María", 28, 1.65
productos = ("Manzanas", "Peras", "Uvas")
producto1, producto2, producto3 = productos
```
### Explicación:

- En el primer ejemplo, se utilizó la asignación múltiple para declarar tres variables en una sola línea.

- En el segundo ejemplo, se desempaquetaron los valores de una tupla en variables individuales.

:::{.callout-tip}
### Actividad Práctica

1. Crea una lista con los nombres de tus tres colores favoritos.

2. Utiliza la asignación múltiple para asignar los valores de la lista a tres variables individuales.

:::

### Explicación de la Actividad

Esta actividad permite a los participantes practicar la asignación múltiple y el desempaquetado de valores. Les ayuda a comprender cómo trabajar eficientemente con múltiples variables y cómo aprovechar estas técnicas para simplificar el código.